# Configuration de l'application
spring.application.name=alert_civique
server.port=9090

# ===============================
# DATASOURCE - MARIADB
# ===============================
spring.datasource.url=jdbc:mariadb://localhost:3307/alertdb
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true


# ===============================
# SQL INIT
# ===============================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# MONGODB CONFIGURATION
# ===============================
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=alertdb
# spring.data.mongodb.uri=mongodb://localhost:27017/alertdb  # Alternative avec URI

# Options supplémentaires (optionnelles)
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.repositories.enabled=true

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.boot.autoconfigure=INFO
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.mongodb=DEBUG